# Exercise 6 - calculation option pnl

The purpose of the this exercise is to demonstrate how to calculate the PNL for an option trade.  In this class, we won't go deep into option pricing and theory, and PNLs will usually be provided for any analysis that you will be doing.  However, this exercise gives a data-focused introduction to these matters.

The data that we will be using for this exercise.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_call = pd.read_csv('../data/spy_call_pnl.csv')
df_call.head()

,underlying,upx,type,expiration,data_date,strike,bid,ask,mid,delta
0,SPY,285.019989,call,2018-09-21,2018-08-17,289,1.39,1.41,1.40,0.297905
1,SPY,285.679993,call,2018-09-21,2018-08-20,289,1.56,1.58,1.57,0.328623
2,SPY,286.269989,call,2018-09-21,2018-08-21,289,1.73,1.75,1.74,0.351140
3,SPY,286.209991,call,2018-09-21,2018-08-22,289,1.53,1.55,1.54,0.335256
4,SPY,285.790009,call,2018-09-21,2018-08-23,289,1.39,1.41,1.40,0.317830

In [3]:
df_call['mid_pnl'] = np.nan
for ix in df_call.index:

    if ix == 0:
        df_call.at[ix, 'mid_pnl'] = 0
    else:
        prev_mid = df_call.at[ix - 1, 'mid']
        curr_mid = df_call.at[ix, 'mid']
        df_call.at[ix, 'mid_pnl'] = prev_mid - curr_mid
    

df_call.head()

,underlying,upx,type,expiration,data_date,strike,bid,ask,mid,delta,mid_pnl
0,SPY,285.019989,call,2018-09-21,2018-08-17,289,1.39,1.41,1.40,0.297905,0.00
1,SPY,285.679993,call,2018-09-21,2018-08-20,289,1.56,1.58,1.57,0.328623,-0.17
2,SPY,286.269989,call,2018-09-21,2018-08-21,289,1.73,1.75,1.74,0.351140,-0.17
3,SPY,286.209991,call,2018-09-21,2018-08-22,289,1.53,1.55,1.54,0.335256,0.20
4,SPY,285.790009,call,2018-09-21,2018-08-23,289,1.39,1.41,1.40,0.317830,0.14

In [14]:
df_call['bid_ask_pnl'] = np.nan
for ix in df_call.index:

    if ix == 0:
        df_call.at[ix, 'bid_ask_pnl'] = \
            df_call.at[ix, 'bid'] - df_call.at[ix, 'ask']
    else:
        prev_ask = df_call.at[ix - 1, 'ask']
        curr_ask = df_call.at[ix, 'ask']
        df_call.at[ix, 'bid_ask_pnl'] = prev_ask - curr_ask
    

df_call.head()

,underlying,upx,type,expiration,data_date,strike,bid,ask,mid,delta,mid_pnl,bid_ask_pnl
0,SPY,285.019989,call,2018-09-21,2018-08-17,289,1.39,1.41,1.40,0.297905,0.00,-0.02
1,SPY,285.679993,call,2018-09-21,2018-08-20,289,1.56,1.58,1.57,0.328623,-0.17,-0.17
2,SPY,286.269989,call,2018-09-21,2018-08-21,289,1.73,1.75,1.74,0.351140,-0.17,-0.17
3,SPY,286.209991,call,2018-09-21,2018-08-22,289,1.53,1.55,1.54,0.335256,0.20,0.20
4,SPY,285.790009,call,2018-09-21,2018-08-23,289,1.39,1.41,1.40,0.317830,0.14,0.14

In [13]:
print(np.sum(df_call['mid_pnl']))     # this is the same as 1.40 - (292.04 - 289)
print(np.sum(df_call['bid_ask_pnl'])) # this is the same as 1.39 - (292.04 - 289)

-1.640008568763733
-1.6500085592269893

In [18]:
np.mean(df_call[df_call.upx > df_call.strike]['delta'])

0.5953252248901814

In [19]:
np.mean(df_call[df_call.upx <= df_call.strike]['delta'])

0.35653435576037906